# Generated by Django 5.0.6 on 2024-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='dean',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='faculty_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='number_of_departments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='student_population',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='current_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='max_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='offered_semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer', 'Summer')], default='Fall', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='accreditation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='faculty_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='student_population',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
