# Generated by Django 5.0.6 on 2024-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_college_annual_budget_college_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.Sc', 'Bachelor of Science'), ('B.A', 'Bachelor of Arts'), ('M.Tech', 'Master of Technology'), ('M.Sc', 'Master of Science'), ('M.A', 'Master of Arts')], max_length=255),
        ),
    ]
