# Generated by Django 5.0.6 on 2024-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0003_alter_course_course_code_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in years'),
        ),
    ]
