# Generated by Django 5.0.6 on 2024-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
