# Generated by Django 5.0.6 on 2024-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_alter_college_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_grade',
            field=models.CharField(blank=True, choices=[('A', 'NAAC A'), ('B', 'NAAC B'), ('C', 'NAAC C'), ('D', 'NAAC D')], default='', max_length=1, null=True),
        ),
    ]
