# Generated by Django 5.0.6 on 2024-06-27 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_university_university_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='university',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
