# Generated by Django 5.0.6 on 2024-06-27 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0008_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
